// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces/user.interface";

export interface DiagramResponse {
  id:          string;
  name:        string;
  description: string;
  data:        string;
  createdAt:   string;
  updatedAt:   null;
  user:        User;
  coWorkers:   any[];
}


