// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces/user.interface";

export interface Diagram {
  id:          number;
  name:        string;
  description: string;
  data:        string;
  user:        User;
  updatedAt:   null;
  createdAt:   string;
}


